// ===========================================
// Supabase Client Configuration
// ===========================================

import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { env } from './env.js';

// Admin client with service role key (bypasses RLS)
// Falls back to anon key if service role not available (limited functionality)
const adminKey = env.SUPABASE_SERVICE_ROLE_KEY || env.SUPABASE_ANON_KEY;
export const supabaseAdmin = createClient(env.SUPABASE_URL, adminKey, {
  auth: {
    autoRefreshToken: false,
    persistSession: false,
  },
});

// Create tenant-scoped client
export const createTenantClient = (tenantId: string): SupabaseClient => {
  const client = createClient(env.SUPABASE_URL, adminKey, {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
    global: {
      headers: {
        // Set tenant context for RLS
        'x-tenant-id': tenantId,
      },
    },
  });

  return client;
};

// Set tenant context via RPC (for RLS)
export const setTenantContext = async (client: SupabaseClient, tenantId: string) => {
  // This sets the app.current_tenant session variable for RLS policies
  const { error } = await client.rpc('set_tenant_context', { tenant_id: tenantId });
  if (error) {
    throw new Error(`Failed to set tenant context: ${error.message}`);
  }
};

// Database types will be generated by Supabase CLI
export type { SupabaseClient };
